---
galaxy_info:
  author: HomeLab Infrastructure
  description: Docker cleanup role for removing orphaned images and containers
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all

dependencies: []