---
galaxy_info:
  author: HomeLab
  description: Docker CE installation for Raspberry Pi (ARM64)
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - docker
    - containers
    - raspberrypi
    - arm64

dependencies: []